$mainMod = SUPER
$launcher = ~/.local/scripts/launcher
$fileManager = ~/.local/scripts/floating-tui yazi

bindd = $mainMod, RETURN, Launch kitty, exec, kitty
bindd = $mainMod, W, Kill active window, killactive,

bindd = $mainMod, H, Move focus left, movefocus, l
bindd = $mainMod, L, Move focus right, movefocus, r
bindd = $mainMod, K, Move focus up, movefocus, u
bindd = $mainMod, J, Move focus down, movefocus, d

bindd = $mainMod SHIFT, H, Move window left, movewindow, l
bindd = $mainMod SHIFT, L, Move window right, movewindow, r
bindd = $mainMod SHIFT, K, Move window up, movewindow, u
bindd = $mainMod SHIFT, J, Move window down, movewindow, d

binddo = $mainMod, K, Swap split, layoutmsg, swapsplit
binddo = $mainMod, J, Toggle split, layoutmsg, togglesplit

bindd = $mainMod, 1, Switch to workspace 1, workspace, 1
bindd = $mainMod, 2, Switch to workspace 2, workspace, 2
bindd = $mainMod, 3, Switch to workspace 3, workspace, 3
bindd = $mainMod, 4, Switch to workspace 4, workspace, 4
bindd = $mainMod, 5, Switch to workspace 5, workspace, 5
bindd = $mainMod, 6, Switch to workspace 6, workspace, 6
bindd = $mainMod, 7, Switch to workspace 7, workspace, 7
bindd = $mainMod, 8, Switch to workspace 8, workspace, 8
bindd = $mainMod, 9, Switch to workspace 9, workspace, 9
bindd = $mainMod, 0, Switch to workspace 10, workspace, 10
bindd = $mainMod, mouse_down, Cycle through workspaces, workspace, e+1
bindd = $mainMod, mouse_up, Cycle through workspaces, workspace, e-1

bindd = $mainMod SHIFT, 1, Move window to workspace 1, movetoworkspace, 1
bindd = $mainMod SHIFT, 2, Move window to workspace 2, movetoworkspace, 2
bindd = $mainMod SHIFT, 3, Move window to workspace 3, movetoworkspace, 3
bindd = $mainMod SHIFT, 4, Move window to workspace 4, movetoworkspace, 4
bindd = $mainMod SHIFT, 5, Move window to workspace 5, movetoworkspace, 5
bindd = $mainMod SHIFT, 6, Move window to workspace 6, movetoworkspace, 6
bindd = $mainMod SHIFT, 7, Move window to workspace 7, movetoworkspace, 7
bindd = $mainMod SHIFT, 8, Move window to workspace 8, movetoworkspace, 8
bindd = $mainMod SHIFT, 9, Move window to workspace 9, movetoworkspace, 9
bindd = $mainMod SHIFT, 0, Move window to workspace 10, movetoworkspace, 10

bindmd = $mainMod, mouse:272, Move window with mouse, movewindow
bindmd = $mainMod, mouse:273, Resize window with mouse, resizewindow
bindd = ,F11, Toggle fullscreen mode of a window, fullscreen

bindd = $mainMod SHIFT, S, Take a Screenshot, exec, screenshot

bindd = $mainMod, ESCAPE, Open the power menu, exec, kitty --class powermenu -e powermenu
# Resize group
bindd = $mainMod SHIFT, R, Enter resize mode, submap, resize

submap = resize

bindde = $mainMod, L, Resize to the right, resizeactive, 10 0
bindde = $mainMod, H, Resize to the right, resizeactive, -10 0
bindde = $mainMod, K, Resize to the right, resizeactive, 0 -10
bindde = $mainMod, J, Resize to the right, resizeactive, 0 10

bind = , escape, submap, reset

submap = reset

bindd = $mainMod, F, Let window float, togglefloating

bindd = $mainMod, SPACE, Open launcher, exec, $launcher
bindd = $mainMod, B, Open browser, exec, firefox
bindd = $mainMod, E, Open file manager, exec, $fileManager

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
