# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = HYPRSHOT_DIR,/home/jamie/Pictures/Screenshots
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER,vulkan

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Other stuff
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
